const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
const FETCH_CATEGORY = 'FETCH_CATEGORY'
const LOADING_CATEGORIES = 'LOADING_CATEGORIES'
const LOADING_CATEGORY = 'LOADING_CATEGORY'
const SET_CATEGORIES = 'SET_CATEGORIES'
const SET_CATEGORY = 'SET_CATEGORY'

export default {
    FETCH_CATEGORIES,
    LOADING_CATEGORIES,
    SET_CATEGORIES,
    FETCH_CATEGORY,
    LOADING_CATEGORY,
    SET_CATEGORY
}