const FETCH_CLIENTS = 'FETCH_CLIENTS'
const FETCH_CLIENT = 'FETCH_CLIENT'
const LOADING_CLIENTS = 'LOADING_CLIENTS'
const LOADING_CLIENT = 'LOADING_CLIENT'
const SET_CLIENTS = 'SET_CLIENTS'
const SET_CLIENT = 'SET_CLIENT'

export default {
    FETCH_CLIENTS,
    LOADING_CLIENTS,
    SET_CLIENTS,
    FETCH_CLIENT,
    LOADING_CLIENT,
    SET_CLIENT
}