const FETCH_CURRENCIES = 'FETCH_CURRENCIES'
const SET_CURRENCIES = 'SET_CURRENCIES'
const LOADING_CURRENCIES = 'LOADING_CURRENCIES'
const FETCH_CURRENCY = 'FETCH_CURRENCY'
const SET_CURRENCY = 'SET_CURRENCY'
const LOADING_CURRENCY = 'LOADING_CURRENCY'

export default {
    FETCH_CURRENCIES,
    SET_CURRENCIES,
    LOADING_CURRENCIES,
    SET_CURRENCY,
    FETCH_CURRENCY,
    LOADING_CURRENCY
}