const FETCH_TRANSACTIONS = 'FETCH_TRANSACTIONS'
const FETCH_TRANSACTION = 'FETCH_TRANSACTION'
const LOADING_TRANSACTIONS = 'LOADING_TRANSACTIONS'
const LOADING_TRANSACTION = 'LOADING_TRANSACTION'
const SET_TRANSACTIONS = 'SET_TRANSACTIONS'
const SET_TRANSACTION = 'SET_TRANSACTION'

export default {
    FETCH_TRANSACTIONS,
    LOADING_TRANSACTIONS,
    SET_TRANSACTIONS,
    FETCH_TRANSACTION,
    LOADING_TRANSACTION,
    SET_TRANSACTION
}