const LOADING_REPORT = 'LOADING_REPORT'
const SET_EXPENSES_FORECAST = 'SET_EXPENSES_FORECAST'
const SET_TRANSACTIONS_FILTERED = 'SET_TRANSACTIONS_FILTERED'

export default {
    LOADING_REPORT,
    SET_EXPENSES_FORECAST,
    SET_TRANSACTIONS_FILTERED
}